project:
  type: website
  output-dir: docs

website:
  title: "Briana Maximino"
  site-url: "https://brianamaximino.github.io/my-portfolio/"
  description: "Marketing portfolio for Briana Maximino, showcasing brand strategy, sports marketing, analytics, dashboards, and digital marketing projects."
  navbar:
    background: light
    pinned: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Marketing Projects"
        href: projects.qmd
      - text: "Dashboard"
        href: dashboard.qmd
      - text: "Presentation"
        href: presentation.qmd
      - text: "Google Analytics"
        href: analytics.qmd
      - text: "Resume"
        href: resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    embed-resources: true